item { 
   id: 1
   name: 'speedLimit15'
 } 
item { 
   id: 2
   name: 'speedLimit25'
 } 
item { 
   id: 3
   name: 'speedLimit30'
 } 
item { 
   id: 4
   name: 'speedLimit35'
 } 
item { 
   id: 5
   name: 'speedLimit40'
 } 
item { 
   id: 6
   name: 'speedLimit45'
 } 
item { 
   id: 7
   name: 'speedLimit50'
 } 
item { 
   id: 8
   name: 'speedLimit60'
 } 
item { 
   id: 9
   name: 'stop'
 } 
item { 
   id: 10
   name: 'stopAhead'
 } 
item { 
   id: 11
   name: 'noParking'
 } 
item { 
   id: 12
   name: 'noLeftAndUTurn'
 } 
item { 
   id: 13
   name: 'noUTurn'
 } 
item { 
   id: 14
   name: 'keepRight'
 } 
item { 
   id: 15
   name: 'noRightTurn'
 } 
item { 
   id: 16
   name: 'doNotEnter'
 } 
item { 
   id: 17
   name: 'leftAndUTurnControl'
 } 
item { 
   id: 18
   name: 'pedestrianCrossing'
 } 
item { 
   id: 19
   name: 'intersectionLaneControl'
 } 
item { 
   id: 20
   name: 'bicyclesMayUseFullLane'
 } 
item { 
   id: 21
   name: 'yieldToPedestrian'
 } 
item { 
   id: 22
   name: 'speedBumpsAhead'
 } 
item { 
   id: 23
   name: 'school'
 } 
item { 
   id: 24
   name: 'yieldAhead'
 } 
item { 
   id: 25
   name: 'intersection'
 } 
item { 
   id: 26
   name: 'addedLane'
 } 
item { 
   id: 27
   name: 'curveLeft'
 } 
item { 
   id: 28
   name: 'curveRight'
 } 
item { 
   id: 29
   name: 'signalAhead'
 } 
item { 
   id: 30
   name: 'merge'
 } 
item { 
   id: 31
   name: 'laneEnds'
 } 